### ISSUE TITLE
Cannot get OAuth token from http:// token provider url.

### ISSUE THREAD

**Issue by rich-allen** [lic-nz/Malone#55]
If you try to get an OAuth token from a token provider url that is not using https, then you get the following error:

This is preventing our testers from using Malone to test our web api's, since the internal test servers are not set up (currently) to use https for the /oauth/token resource.

**Comment by stajs** [comment]
http://stackoverflow.com/questions/6265944/dotnetopenauth-throws-a-protocolexception

**Comment by rich-allen** [comment]
so you're saying (or not) to include the test server names for the sts token providers to the server whitelist in config files???

**Comment by stajs** [comment]
Sorry, that link without context was simply a reminder for when I came back to this issue - I ran out of time to fully investigate. When you try to authenticate against an OAuth provider, the response you see is from the server, not an error in Malone. So the response:

> This message can only be sent over HTTPS.

... means the server doesn't allow you to request an OAuth token over HTTP. With DotNetOpenAuth, there is a setting to `relaxSslRequirements` so that HTTP will work. You'll have to update the web.config for the server to allow it. An example config is here:

https://github.com/DotNetOpenAuth/DotNetOpenAuth/blob/master/samples/OAuthClient/Web.config

**Comment by stajs** [comment]
I think I might have been lying. Re-opening until I can further investigate, but my thinking now is that both ends have to allow it (`relaxSslRequirements`).

**Comment by rich-allen** [comment]
cool. i think you may be right. After updating the webserver, Stacy still has the problem, but I don't.....

**Comment by stajs** [comment]
Replace `%LocalAppData%\Malone\app-0.4.0\Malone.exe.config` with the following:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<configSections>
		<sectionGroup name="dotNetOpenAuth" type="DotNetOpenAuth.Configuration.DotNetOpenAuthSection, DotNetOpenAuth">
			<section name="messaging" type="DotNetOpenAuth.Configuration.MessagingElement, DotNetOpenAuth" requirePermission="false" allowLocation="true" />
		</sectionGroup>
	</configSections>
	<appSettings>
		<add key="UpdateUrl" value="http://ninja.co.nz/malone/releases" />
	</appSettings>
	<system.net>
		<defaultProxy useDefaultCredentials="true" />
	</system.net>
	<dotNetOpenAuth>
		<messaging relaxSslRequirements="true" />
	</dotNetOpenAuth>
</configuration>
```
